name: qj

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build-windows:
    name: build windows
    runs-on: windows-latest
    steps:
      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.6
          
      - name: checkout
        uses: actions/checkout@v2
        
      - name: install deps
        run: go get -v -d ./...
      
      - name: build
        run: go build -v
      
      - name: archive binary
        uses: actions/upload-artifact@v1
        with:
          name: qj
          path: qj.exe
